import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import StatusBar from "@/components/StatusBar";
import ReactQueryProvider from "@/providers/ReactQueryProvider";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Payment Web Application for Delight Labs from SeonWoo Han",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen border bg-background font-sans antialiased",
          inter.variable,
        )}
      >
        <ReactQueryProvider>
          <StatusBar />
          {children}
        </ReactQueryProvider>
      </body>
    </html>
  );
}
